kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang
  commands:
  - go build
- name: publish
  image: plugins/github-release
  settings:
    api_key: xxxxxxxx
    files: dist/*