kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang
  commands:
  - mkdir dist
  - go build -o dist/
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: dist/*
  when:
    event: tag